sudo: required
srvices:
  - docker

before_install:
  - docker build -t sliron1989/docker-react -f Dockerfile.dev .

script:
  - docker run sliron1989/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk 
  region: "us-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-485107509892"
  endpoint: "https://s3.us-east-2.amazonaws.com"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: 
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"